export const LOADING_TOYS_SUCCESS = "LOADING_TOYS_SUCCESS";
export const LOADING_TOYS_FAILED = "LOADING_TOYS_FAILED";
export const LOADING_TOY_SUCCESS = "LOADING_TOY_SUCCESS";
export const LOADING_TOY_FAILED = "LOADING_TOY_FAILED";
export const LOADING_TOY_BEGIN = "LOADING_TOY_BEGIN";
export const LOADING = "LOADING";
export const LOADING_SINGLE = "LOADING_SINGLE";
